// Copyright (c) 2026 Roman Zhuzhgov
// Licensed under the Apache License, Version 2.0

import Foundation
import IrisCLICore
import Testing

/// Byte-locks the CLI's listing output against the goldens generated by
/// `Scripts/build-cli-fixtures.sh`: plain listings for every well-formed
/// fixture shape (thin, arm64e, fat, stripped, MH_OBJECT, linked
/// data-in-code), the `--semantics` listing, and column/label structure.
/// Comparison normalizes only the absolute fixture-path prefix.
@Suite("Listing goldens")
struct ListingGoldenTests {
    /// Run a color-never listing and compare to a locked golden.
    func expectGolden(arguments: [String], fixture: String, goldenName: String) {
        let run = runCLI(arguments + [cliFixturePath(fixture)])
        #expect(run.status == CLI.exitSuccess)
        #expect(run.stderr.isEmpty)
        #expect(normalizedToGolden(run.stdout) == golden(goldenName))
    }

    @Test func thinARM64Listing() {
        expectGolden(arguments: ["--color", "never"], fixture: "hello-arm64", goldenName: "hello-arm64.listing.txt")
    }

    @Test func arm64eListing() {
        expectGolden(arguments: ["--color", "never"], fixture: "hello-arm64e", goldenName: "hello-arm64e.listing.txt")
    }

    @Test func fatDefaultSliceListing() {
        expectGolden(arguments: ["--color", "never"], fixture: "hello-fat", goldenName: "hello-fat.listing.txt")
    }

    @Test func strippedListingUsesSubLabels() {
        expectGolden(arguments: ["--color", "never"], fixture: "hello-stripped", goldenName: "hello-stripped.listing.txt")
        let run = runCLI(["--color", "never", cliFixturePath("hello-stripped")])
        #expect(run.stdout.contains("sub_100000328:"))
        #expect(!run.stdout.contains("_add42"))
    }

    @Test func objectFileDataInCodeListing() {
        expectGolden(arguments: ["--color", "never"], fixture: "dic-arm64.o", goldenName: "dic-arm64.listing.txt")
        let run = runCLI(["--color", "never", cliFixturePath("dic-arm64.o")])
        #expect(run.stdout.contains(".long 0x6040200 ; data-in-code (jump-table-8)"))
        #expect(run.stdout.contains(".long 0xdeadbeef ; data-in-code (data)"))
    }

    @Test func linkedDataInCodeListing() {
        expectGolden(arguments: ["--color", "never"], fixture: "dic-linked", goldenName: "dic-linked.listing.txt")
    }

    @Test func semanticsListing() {
        expectGolden(
            arguments: ["--color", "never", "--semantics"],
            fixture: "hello-arm64",
            goldenName: "hello-arm64.semantics.txt",
        )
    }

    @Test func callsAreSymbolicated() {
        let run = runCLI(["--color", "never", cliFixturePath("hello-arm64")])
        #expect(run.stdout.contains("bl 0x100000328 ; _add42"))
        #expect(run.stdout.contains("bl 0x100000340 ; _sum_to"))
        #expect(run.stdout.contains("bl 0x100000398 ; _helper"))
    }

    @Test func stubBranchAnnotatesTheImport() {
        expectGolden(arguments: ["--color", "never"], fixture: "stub-arm64", goldenName: "stub-arm64.listing.txt")
        let run = runCLI(["--color", "never", cliFixturePath("stub-arm64")])
        #expect(run.stdout.contains("b 0x10000042c ; symbol stub for: _strcoll"))
    }

    @Test func stubSymbolicationSurvivesStripping() {
        expectGolden(arguments: ["--color", "never"], fixture: "stub-stripped", goldenName: "stub-stripped.listing.txt")
        let run = runCLI(["--color", "never", cliFixturePath("stub-stripped")])
        // The import name still resolves through the stub even with no
        // symbol table, while the function it sits in is a sub_ label.
        #expect(run.stdout.contains("; symbol stub for: _strcoll"))
        #expect(run.stdout.contains("sub_100000410:"))
    }

    @Test func intraFunctionBranchesCarryOffsetForm() {
        let run = runCLI(["--color", "never", cliFixturePath("hello-arm64")])
        #expect(run.stdout.contains("b.ge 0x10000038c ; _sum_to+0x4c"))
    }

    @Test func everyFunctionLabelPresent() {
        let run = runCLI(["--color", "never", cliFixturePath("hello-arm64")])
        for label in ["_add42:", "_sum_to:", "_helper:", "_main:"] {
            #expect(run.stdout.contains("\n" + label + "\n"))
        }
        #expect(run.stdout.contains("__TEXT,__text:"))
    }

    @Test func semanticsColumnIsAligned() {
        let run = runCLI(["--color", "never", "--semantics", cliFixturePath("hello-arm64")])
        let annotated = run.stdout.split(separator: "\n").filter { $0.contains("; reads=") || $0.contains("; writes=") }
        #expect(!annotated.isEmpty)
        // The semantics annotation is the line's last "; "; every body in
        // this fixture fits the fixed column, so they all start at
        // 9-digit address + ":" + space + 8-digit word + 2 spaces (21)
        // plus the 44-column body field.
        let columns = Set(annotated.compactMap { line -> Int? in
            guard let range = line.range(of: "; ", options: .backwards) else { return nil }
            return line.distance(from: line.startIndex, to: range.lowerBound)
        })
        #expect(columns == [21 + 44])
    }
}
