// Copyright (c) 2026 Roman Zhuzhgov
// Licensed under the Apache License, Version 2.0

public extension Mnemonic {
    static let adclb = Mnemonic(rawValue: 16469)
    static let adclt = Mnemonic(rawValue: 16470)
    static let sabalb = Mnemonic(rawValue: 16525)
    static let sabalt = Mnemonic(rawValue: 16526)
    static let sbclb = Mnemonic(rawValue: 16535)
    static let sbclt = Mnemonic(rawValue: 16536)
    static let smlalb = Mnemonic(rawValue: 16544)
    static let smlalt = Mnemonic(rawValue: 16545)
    static let smlslb = Mnemonic(rawValue: 16546)
    static let smlslt = Mnemonic(rawValue: 16547)
    static let smullb = Mnemonic(rawValue: 16548)
    static let sqdmlalb = Mnemonic(rawValue: 16553)
    static let sqdmlalbt = Mnemonic(rawValue: 16554)
    static let sqdmlalt = Mnemonic(rawValue: 16555)
    static let sqdmlslb = Mnemonic(rawValue: 16556)
    static let sqdmlslbt = Mnemonic(rawValue: 16557)
    static let sqdmlslt = Mnemonic(rawValue: 16558)
    static let sqdmullt = Mnemonic(rawValue: 16560)
    static let uabalb = Mnemonic(rawValue: 16589)
    static let uabalt = Mnemonic(rawValue: 16590)
    static let umlalb = Mnemonic(rawValue: 16603)
    static let umlalt = Mnemonic(rawValue: 16604)
    static let umlslb = Mnemonic(rawValue: 16605)
    static let umlslt = Mnemonic(rawValue: 16606)

    static let addhnb = Mnemonic(rawValue: 16471)
    static let addhnt = Mnemonic(rawValue: 16472)
    static let raddhnb = Mnemonic(rawValue: 16519)
    static let raddhnt = Mnemonic(rawValue: 16520)
    static let rshrnb = Mnemonic(rawValue: 16521)
    static let rshrnt = Mnemonic(rawValue: 16522)
    static let rsubhnb = Mnemonic(rawValue: 16523)
    static let rsubhnt = Mnemonic(rawValue: 16524)
    static let shrnb = Mnemonic(rawValue: 16539)
    static let shrnt = Mnemonic(rawValue: 16540)
    static let sqcvtn = Mnemonic(rawValue: 16551)
    static let sqcvtun = Mnemonic(rawValue: 16552)
    static let sqrshrnb = Mnemonic(rawValue: 16563)
    static let sqrshrnt = Mnemonic(rawValue: 16564)
    static let sqrshrunb = Mnemonic(rawValue: 16565)
    static let sqrshrunt = Mnemonic(rawValue: 16566)
    static let sqshrnb = Mnemonic(rawValue: 16568)
    static let sqshrnt = Mnemonic(rawValue: 16569)
    static let sqshrunb = Mnemonic(rawValue: 16570)
    static let sqshrunt = Mnemonic(rawValue: 16571)
    static let sqxtnb = Mnemonic(rawValue: 16573)
    static let sqxtnt = Mnemonic(rawValue: 16574)
    static let sqxtunb = Mnemonic(rawValue: 16575)
    static let sqxtunt = Mnemonic(rawValue: 16576)
    static let subhnb = Mnemonic(rawValue: 16586)
    static let subhnt = Mnemonic(rawValue: 16587)
    static let uqcvtn = Mnemonic(rawValue: 16609)
    static let uqrshrnb = Mnemonic(rawValue: 16611)
    static let uqrshrnt = Mnemonic(rawValue: 16612)
    static let uqshrnb = Mnemonic(rawValue: 16614)
    static let uqshrnt = Mnemonic(rawValue: 16615)
    static let uqxtnb = Mnemonic(rawValue: 16617)
    static let uqxtnt = Mnemonic(rawValue: 16618)

    static let addqp = Mnemonic(rawValue: 16473)
    static let addsubp = Mnemonic(rawValue: 16475)

    static let addqv = Mnemonic(rawValue: 16474)
    static let andqv = Mnemonic(rawValue: 16476)
    static let andv = Mnemonic(rawValue: 16477)
    static let eorqv = Mnemonic(rawValue: 16501)
    static let eorv = Mnemonic(rawValue: 16503)
    static let orqv = Mnemonic(rawValue: 16515)
    static let orv = Mnemonic(rawValue: 16516)
    static let saddv = Mnemonic(rawValue: 16532)
    static let smaxqv = Mnemonic(rawValue: 16542)
    static let sminqv = Mnemonic(rawValue: 16543)
    static let uaddv = Mnemonic(rawValue: 16595)
    static let umaxqv = Mnemonic(rawValue: 16601)
    static let uminqv = Mnemonic(rawValue: 16602)

    static let asrd = Mnemonic(rawValue: 16478)
    static let asrr = Mnemonic(rawValue: 16479)
    static let lslr = Mnemonic(rawValue: 16506)
    static let lsrr = Mnemonic(rawValue: 16507)

    static let bdep = Mnemonic(rawValue: 16480)
    static let bext = Mnemonic(rawValue: 16481)
    static let bgrp = Mnemonic(rawValue: 16482)
    static let eorbt = Mnemonic(rawValue: 16500)
    static let eortb = Mnemonic(rawValue: 16502)
    static let histcnt = Mnemonic(rawValue: 16504)
    static let histseg = Mnemonic(rawValue: 16505)
    static let match = Mnemonic(rawValue: 16510)
    static let nmatch = Mnemonic(rawValue: 16514)
    static let pmullb = Mnemonic(rawValue: 16517)
    static let pmullt = Mnemonic(rawValue: 16518)
    static let sabdlb = Mnemonic(rawValue: 16527)
    static let sabdlt = Mnemonic(rawValue: 16528)
    static let saddlb = Mnemonic(rawValue: 16529)
    static let saddlbt = Mnemonic(rawValue: 16530)
    static let saddlt = Mnemonic(rawValue: 16531)
    static let saddwb = Mnemonic(rawValue: 16533)
    static let saddwt = Mnemonic(rawValue: 16534)
    static let smullt = Mnemonic(rawValue: 16549)
    static let sqdmullb = Mnemonic(rawValue: 16559)
    static let ssublb = Mnemonic(rawValue: 16580)
    static let ssublbt = Mnemonic(rawValue: 16581)
    static let ssublt = Mnemonic(rawValue: 16582)
    static let ssubltb = Mnemonic(rawValue: 16583)
    static let ssubwb = Mnemonic(rawValue: 16584)
    static let ssubwt = Mnemonic(rawValue: 16585)
    static let uabdlb = Mnemonic(rawValue: 16591)
    static let uabdlt = Mnemonic(rawValue: 16592)
    static let uaddlb = Mnemonic(rawValue: 16593)
    static let uaddlt = Mnemonic(rawValue: 16594)
    static let uaddwb = Mnemonic(rawValue: 16596)
    static let uaddwt = Mnemonic(rawValue: 16597)
    static let umullb = Mnemonic(rawValue: 16607)
    static let umullt = Mnemonic(rawValue: 16608)
    static let usublb = Mnemonic(rawValue: 16622)
    static let usublt = Mnemonic(rawValue: 16623)
    static let usubwb = Mnemonic(rawValue: 16624)
    static let usubwt = Mnemonic(rawValue: 16625)

    static let bsl1n = Mnemonic(rawValue: 16483)
    static let bsl2n = Mnemonic(rawValue: 16484)
    static let nbsl = Mnemonic(rawValue: 16513)

    static let cadd = Mnemonic(rawValue: 16485)
    static let cdot = Mnemonic(rawValue: 16486)
    static let cmla = Mnemonic(rawValue: 16487)
    static let sqcadd = Mnemonic(rawValue: 16550)
    static let sqrdcmlah = Mnemonic(rawValue: 16561)

    static let cmpeq = Mnemonic(rawValue: 16488)
    static let cmpge = Mnemonic(rawValue: 16489)
    static let cmpgt = Mnemonic(rawValue: 16490)
    static let cmphi = Mnemonic(rawValue: 16491)
    static let cmphs = Mnemonic(rawValue: 16492)
    static let cmple = Mnemonic(rawValue: 16493)
    static let cmplo = Mnemonic(rawValue: 16494)
    static let cmpls = Mnemonic(rawValue: 16495)
    static let cmplt = Mnemonic(rawValue: 16496)
    static let cmpne = Mnemonic(rawValue: 16497)

    static let cnot = Mnemonic(rawValue: 16498)
    static let uxtw = Mnemonic(rawValue: 16626)

    static let dupm = Mnemonic(rawValue: 16499)

    static let mad = Mnemonic(rawValue: 16508)
    static let msb = Mnemonic(rawValue: 16512)

    static let madpt = Mnemonic(rawValue: 16509)
    static let mlapt = Mnemonic(rawValue: 16511)

    static let sclamp = Mnemonic(rawValue: 16537)
    static let uclamp = Mnemonic(rawValue: 16598)

    static let sdivr = Mnemonic(rawValue: 16538)
    static let udivr = Mnemonic(rawValue: 16599)

    static let shsubr = Mnemonic(rawValue: 16541)
    static let sqrshlr = Mnemonic(rawValue: 16562)
    static let sqshlr = Mnemonic(rawValue: 16567)
    static let sqsubr = Mnemonic(rawValue: 16572)
    static let srshlr = Mnemonic(rawValue: 16577)
    static let uhsubr = Mnemonic(rawValue: 16600)
    static let uqrshlr = Mnemonic(rawValue: 16610)
    static let uqshlr = Mnemonic(rawValue: 16613)
    static let uqsubr = Mnemonic(rawValue: 16616)
    static let urshlr = Mnemonic(rawValue: 16619)

    static let sshllb = Mnemonic(rawValue: 16578)
    static let sshllt = Mnemonic(rawValue: 16579)
    static let ushllb = Mnemonic(rawValue: 16620)
    static let ushllt = Mnemonic(rawValue: 16621)

    static let subr = Mnemonic(rawValue: 16588)
}
